// Weak stub implementations for CUDA device code registration symbols
// These symbols are generated by nvcc and should be provided by CUDA runtime
// We provide weak stubs to allow linking, and the CUDA runtime will override them at runtime

#include <stdint.h>
#include <stddef.h>

// Forward declarations for CUDA types (simplified)
typedef struct { int x, y, z; } dim3;
typedef struct { unsigned int x, y, z; } uint3;

// Weak stub implementations - CUDA runtime will provide real ones at runtime
// These functions return void* but the actual signature may vary
// We provide minimal stubs that return NULL
__attribute__((weak))
void* __cudaRegisterLinkedBinary_2c9b6a98_8_curve_cu_5ce60628(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

// Updated hash for curve.cu after removing init_device_curve and changing casts
__attribute__((weak))
void* __cudaRegisterLinkedBinary_2c9b6a98_8_curve_cu_3d6d16e6(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_6f717f17_12_c_wrapper_cu_c2ca44b5(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_b50fa345_9_device_cu_1c0282e3(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_0e52b419_5_fp_cu_6531ec1d(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

// Updated hash for fp.cu after hardcoding constants
__attribute__((weak))
void* __cudaRegisterLinkedBinary_0e52b419_5_fp_cu_7874d10b(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_0e52b419_5_fp_cu_fc9d9070(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_e81dd329_6_fp2_cu_fa47e05b(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

// Additional CUDA registration symbols
__attribute__((weak))
void* __cudaRegisterLinkedBinary_2a86d19e_14_fp2_kernels_cu_f2405ec3(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

__attribute__((weak))
void* __cudaRegisterLinkedBinary_b8c07a4e_13_fp_kernels_cu_6a15da5c(void* a, void* b, void* c, void* d, void* e, void* f, void* g, void* h, void* i, void* j, void* k) {
    (void)a; (void)b; (void)c; (void)d; (void)e; (void)f; (void)g; (void)h; (void)i; (void)j; (void)k;
    return (void*)0;
}

// CUDA runtime registration functions (should be provided by libcudart.so)
__attribute__((weak))
void __cudaRegisterFunction(void** fatCubinHandle, void* hostFun, char* deviceFun, const char* deviceName, int thread_limit, uint3* tid, uint3* bid, dim3* bDim, dim3* gDim, int* wSize) {
    (void)fatCubinHandle; (void)hostFun; (void)deviceFun; (void)deviceName; (void)thread_limit;
    (void)tid; (void)bid; (void)bDim; (void)gDim; (void)wSize;
}

__attribute__((weak))
void __cudaRegisterVar(void** fatCubinHandle, char* hostVar, char* deviceAddress, const char* deviceName, int ext, int size, int constant, int global) {
    (void)fatCubinHandle; (void)hostVar; (void)deviceAddress; (void)deviceName;
    (void)ext; (void)size; (void)constant; (void)global;
}

__attribute__((weak))
void __cudaPushCallConfiguration(dim3 gridDim, dim3 blockDim, size_t sharedMem, void* stream) {
    (void)gridDim; (void)blockDim; (void)sharedMem; (void)stream;
}

__attribute__((weak))
void __cudaPopCallConfiguration(void) {
}

